"""initial schema: guardian, dependant, balance, ledgertransaction

Revision ID: 7f0c8bdade52
Revises:
Create Date: 2026-06-17

This first migration was produced with ``alembic revision --autogenerate`` and
is the realistic workflow candidates extend when they add the spending-limits
model:

    # after editing app/models.py
    alembic revision --autogenerate -m "add spending limit"
    alembic upgrade head

(The app also creates tables on startup via ``create_db_and_tables()``, so
migrations are not required just to run the app locally.)
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f0c8bdade52'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guardian_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dependant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependant_guardian_id'), ['guardian_id'], unique=False)

    op.create_table('balance',
    sa.Column('dependant_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['dependant_id'], ['dependant.id'], ),
    sa.PrimaryKeyConstraint('dependant_id')
    )
    op.create_table('ledgertransaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dependant_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('FUNDING', 'SPEND', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dependant_id'], ['dependant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledgertransaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledgertransaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledgertransaction_dependant_id'), ['dependant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledgertransaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledgertransaction_dependant_id'))
        batch_op.drop_index(batch_op.f('ix_ledgertransaction_created_at'))

    op.drop_table('ledgertransaction')
    op.drop_table('balance')
    with op.batch_alter_table('dependant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependant_guardian_id'))

    op.drop_table('dependant')
    op.drop_table('guardian')
    # ### end Alembic commands ###
